# From: https://www.snoyman.com/blog/2016/08/appveyor-haskell-windows-ci

build: off

before_test:
# http://help.appveyor.com/discussions/problems/6312-curl-command-not-found
- mkdir .local\bin
- set PATH=%CD%\.local\bin;C:\MinGW\bin;C:\Program Files\Git\mingw64\bin;%PATH%

- curl -sS -ostack.zip -L --insecure http://www.stackage.org/stack/windows-i386
- 7z e -o.local\bin stack.zip stack.exe

- curl -sS -ographviz.zip -L --insecure https://graphviz.gitlab.io/_pages/Download/windows/graphviz-2.38.zip
- 7z e -o.local\bin graphviz.zip release\bin

clone_folder: "c:\\stack"
environment:
  global:
    STACK_ROOT: "c:\\sr"

test_script:
- stack setup > nul
- mingw32-make build examples STACK_FLAGS="--no-terminal"
