# This is the simple Travis configuration, which is intended for use
# on applications which do not require cross-platform and
# multiple-GHC-version support. For more information and other
# options, see:
#
# https://docs.haskellstack.org/en/stable/travis_ci/
#
# Copy these contents into the root directory of your Github project in a file
# named .travis.yml

# Use new container infrastructure to enable caching
sudo: false

# Do not choose a language; we provide our own build tools.
language: generic

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

# Ensure necessary system libraries are present
addons:
  apt:
    packages:
      - libgmp-dev

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

- sudo apt-get -qq update
- sudo apt-get install -y graphviz
- sudo apt-get install -y chrpath fakeroot

- sudo apt-get install --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra texlive-latex-recommended dvipng
- sudo pip install rst2pdf

install:
# Build dependencies
- stack --no-terminal --install-ghc test --only-dependencies

script:
# Build the package, its tests, and its docs and run the tests
- make package examples doc STACK_FLAGS="--no-terminal" CABAL_FLAGS="--haddock --no-haddock-deps"

deploy:
  provider: releases
  api_key:
    secure: c/Xo3n9gmvI7l23+/fNuuuiGATJSTmZkSEKhmNO4jEhBkIqV3eEectSL/3SJSMkGzpe42kisgQXJzXDjuPvPmjz+a4pkKzBfS9qAaKO/299dP4f4Kb7DhaTy3s7OI6a+8xaaWsa0wytkHdLlbCMrqHfPdoa6IG8Cir+WlC2TK+IJIElTrH4y0eAKAlsoxy8qeV6FX8G9JruU1JWXF7UUELXwiYVPXXS0kIX9gZ8hRTxgilDrgFRIah9NvEOg20W2OEH5IXKU4d/xt8/xATr5IQh5kGLUKUUKJWORw71TTDszqheQNiLfeoRcb3Q2VVa84+7AhpQMLsNCQVcnlZLiYeNqR55E7Z0YjBOcFS6msRRjRKd2eU0bxBadLKNH+VHBY8UCGKr5GwEFFI3ECDiDecxQOidj+CJ6Y2DMxS3MjeXQRA9U4eLsStlKmP7yj4UuDfYAuHl39TbHxlRQO7Ra9vD5ev4dIasET/QpoH4rO9R0B9byriUwjGcqdLrJ6VHJNcHlTphMClhsx2ywT55DIKxMGuuvEoJe0yOWYu2xTGghSuSCxyv1kf5m9p4u0F1fuPf3FC2A7dPXH+wHtPbcBMZYM3RVB085Kx69MOxcNqOVDGbYwWZkZmgpRFPAfj+sF9nbYRyq+kddsx/j/Zi+dCK6JCxGzVsAtapKVwPHP20=
  file_glob: true
  file: smudge_*_*.*
  skip_cleanup: true
  on:
    repo: smudgelang/smudge
    branch: master
    tags: true
